### ISSUE TITLE
[Epic#6] pc버전의 헤더 스타일을 완성한다

### ISSUE THREAD

**Issue by happydhKim** [happydhKim/search-place-front#11]
# [Epic#6] pc버전의 헤더 스타일을 완성한다.

- pc버전의 헤더 스타일을 완성해야 한다.

## 완료 조건 ✅

- [x] 헤더의 기본적인 틀 및 style을 구현한다.
- [x] 헤더에 사용 될 버튼을 구현한다.
- [x] 파비콘을 적용한다.
- [x] 헤더의 영역 별 버튼 및 기능을 구현한다.
- [x] 제대로 구현이 되었는지 테스트 및 확인을 진행한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
