### ISSUE TITLE
[Epic#7] mobile버전의 헤더 스타일을 완성한다

### ISSUE THREAD

**Issue by happydhKim** [happydhKim/search-place-front#12]
# [Epic#7] mobile버전의 헤더 스타일을 완성한다.

- mobile버전의 헤더 스타일을 완성해야 한다.

## 완료 조건 ✅

- [x] 헤더의 기본적인 틀 및 style을 구현한다.
- [x] 헤더에 사용 될 버튼을 구현한다.
- [x] 파비콘을 적용한다.
- [x] 헤더의 영역 별 버튼 및 기능을 구현한다.
- [x] 제대로 구현이 되었는지 테스트 및 확인을 진행한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by happydhKim** [comment]
모바일 버전에서 메뉴가 popover대신 페이지로 나누는 부분이 있는데 해당 페이지는 추 후에 feature로 할당한다.
