### ISSUE TITLE
[Epic#8] pc와 mobile 스타일을 다듬고 페이지를 연동한다

### ISSUE THREAD

**Issue by happydhKim** [happydhKim/search-place-front#13]
# [Epic#8] pc와 mobile 스타일을 다듬고 페이지를 연동한다

- pc와 mobile 스타일을 다듬고 페이지를 연동해야 한다.

## 완료 조건 ✅

- [x] 플랫폼 별 반응형이 작동되어야 한다.
- [x] 플랫폼 별 스타일이 일관성 있어야 한다.
- [ ] 플랫폼 별 기능을 연동시켜야 한다.
- [x] 리팩토링이 가능 한 부분을 찾아보고 비용이 적으면 리팩토링을 한다. 비용이 클 경우 문서를 작성한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
