### ISSUE TITLE
[Epic#9] 재사용 가능한 popover를 구현한다

### ISSUE THREAD

**Issue by happydhKim** [happydhKim/search-place-front#14]
# [Epic#9] 재사용 가능한 popover를 구현한다.

- 재사용 가능한 popover를 구현해야 한다.

## 완료 조건 ✅

- [x] popover 컴포넌트를 생성한다.
- [x] popover 가 작동하는지 확인한다.
- [x] popover 에 props를 통해 크기를 설정 할 수 있게 한다. ( 수정 될 수 있음 )
- [ ] popover 가 플랫폼 별 다르게 나타나야 한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
