### ISSUE TITLE
[Epic#10] popover를 이용해 카테고리 및 회원 정보 popover창을 구현한다

### ISSUE THREAD

**Issue by happydhKim** [happydhKim/search-place-front#15]
# [Epic#10] popover를 이용해 카테고리 및 회원 정보 popover창을 구현한다

- popover를 이용해 카테고리 및 회원 정보 popover창을 구현해야 한다.

## 완료 조건 ✅

- [ ] 카테고리를 기획 및 설정한다.
- [ ] popover를 이용해 카테고리 popover를 만든다.
- [ ] 회원 정보를 기획 및 설정한다.
- [ ] popover를 이용해 회원 정보 popover를 만든다.
- [ ] popover 기능을 연동한다.
- [ ] 플랫폼 별 잘 작동하는지 확인한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
